name: publish
on:
  workflow_dispatch:
    inputs:
      tag:
        description: build tag
        required: false
jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the hello-docker Docker image
      run: |
         docker build . --tag ghcr.io/openimis/openimis-mssql:${{ github.event.inputs.tag }}
         docker run ghcr.io/openimis/openimis-mssql:${{ github.event.inputs.tag }}
         docker push ghcr.io/openimis/openimis-mssql:${{ github.event.inputs.tag }}
