name: Merge SQL files
# This workflow run automatically for every commit on github it checks the syntax and launch the tests.
# | grep . | uniq -c filters out empty lines and then groups consecutive lines together with the number of occurrences
on:
  pull_request:
  workflow_dispatch:
    inputs:
      comment:
        description: Just a simple comment to know the purpose of the manual build
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Merge me!
        run : |
          mkdir output
          cat Migration\ script/openIMIS\ migration\ latest.sql Migration\ script/storedProcedures/* > output/fullMigrationScipt.sql
          cat Empty\ databases/openIMIS_ONLINE.sql Migration\ script/storedProcedures/* > output/fullEmptyDatabase.sql
          cat Empty\ databases/openIMIS_ONLINE.sql  Demo\ database/openIMIS_demo_ONLINE.sql Migration\ script/storedProcedures/* > output/fullDemoDatabase.sql
      - name: Publish artifact
        uses: actions/upload-artifact@master
        with:
          name: sql-files
          path: output 
