name: Automated CI testing
# This workflow run automatically for every commit on github it checks the syntax and launch the tests.
# | grep . | uniq -c filters out empty lines and then groups consecutive lines together with the number of occurrences
on:
  pull_request:
  workflow_dispatch:
    inputs:
      comment:
        description: Just a simple comment to know the purpose of the manual build
        required: false

jobs:
  run_test:
    runs-on: ubuntu-latest
    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2017-latest
        env:
          ACCEPT_EULA: Y
          SA_PASSWORD: GitHub999
        ports:
          - 1433:1433
        # needed because the mssql container does not provide a health check
        options: --health-interval=10s --health-timeout=3s --health-start-period=10s --health-retries=10 --health-cmd="/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -Q 'SELECT 1' || exit 1"

    steps:
      - name: copy current branch
        uses: actions/checkout@v2
        with:
          path: './new'
      - name: install linux packages
        run: |
          mkdir ./oldMain 
          wget https://raw.githubusercontent.com/openimis/database_ms_sqlserver/main/Empty%20databases/openIMIS_ONLINE.sql -O oldMain/openIMIS_ONLINE.sql
          wget https://raw.githubusercontent.com/openimis/database_ms_sqlserver/main/Demo%20database/openIMIS_demo_ONLINE.sql -O oldMain/openIMIS_demo_ONLINE.sql
          mkdir ./1.30
          wget https://raw.githubusercontent.com/openimis/database_ms_sqlserver/v1.3.0/Empty databases/openIMIS_ONLINE.sql -O 1.30/openIMIS_ONLINE.sql
          wget https://raw.githubusercontent.com/openimis/database_ms_sqlserver/v1.3.0/Empty databases/openIMIS_demo_ONLINE.sql -O 1.30/openIMIS_demo_ONLINE.sql          
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
          curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y  mssql-tools build-essential dialog apt-utils unixodbc-dev -y
      - name: Initialize DB latest
        run: |
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'DROP DATABASE IF EXISTS imis'
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'CREATE DATABASE imis'
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i "new/Empty databases/openIMIS_ONLINE.sql" | grep . | uniq -c
          /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i "new/openIMIS_demo_ONLINE.sql" | grep . | uniq -c
        env:
          SA_PASSWORD: GitHub999
          ACCEPT_EULA: Y
      - name: DB migration prev main
        run: |
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'DROP DATABASE IF EXISTS imis'
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'CREATE DATABASE imis'
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i oldMain/openIMIS_ONLINE.sql | grep . | uniq -c
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i oldMain/openIMIS_demo_ONLINE.sql | grep . | uniq -c
        /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i "new/Migration script/openIMIS_demo_ONLINE.sql" | grep . | uniq -c
        env:
        SA_PASSWORD: GitHub999
        ACCEPT_EULA: Y
      - name: DB migration 1.30
        run: |
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'DROP DATABASE IF EXISTS imis'
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -Q 'CREATE DATABASE imis'
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i 1.30/openIMIS_ONLINE.sql | grep . | uniq -c
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i 1.30/openIMIS_demo_ONLINE.sql | grep . | uniq -c
            /opt/mssql-tools/bin/sqlcmd -S localhost,1433 -U SA -P $SA_PASSWORD -d imis -i "new/Migration script/openIMIS_demo_ONLINE.sql" | grep . | uniq -c
        env:
            SA_PASSWORD: GitHub999
            ACCEPT_EULA: Y